spring:
  application:
    name: ${{values.component_id}}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


server:
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER
  servlet:
    context-path: /v1


