spring:

  datasource:
      username: sa
      password:
      url: jdbc:h2:mem:${{values.db_name}}
      #url: jdbc:h2:file:/data/demo
      driver-class-name: org.h2.Driver
      test-while-idle: true
      validation-query: SEELCT 1
  jpa:
     properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

