spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/${{values.db_name}}?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 12345

  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    database: MYSQL
    generate-ddl: false

logging:
  level:
    org.hibernate.type: trace
